name: mongo_dart_relations
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: teja <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  mongo_dart:
  jaguar_serializer:

dev_dependencies:
  test: ^0.12.0
